webtalk_init -webtalk_dir /home/fabio/Desktop/linreg/linreg.tmp/gradientdescent_v1_0_project/gradientdescent_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/MiniBatchGradientDescentTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 10 00:11:03 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "290bab19-d7e7-4e72-945e-b166cdaffefe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ec8588b8ea9a49ada81aa04e4b16a32c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1408.087 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "137468_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2442845916 -regid "" -xml /home/fabio/Desktop/linreg/linreg.tmp/gradientdescent_v1_0_project/gradientdescent_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/MiniBatchGradientDescentTest_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fabio/Desktop/linreg/linreg.tmp/gradientdescent_v1_0_project/gradientdescent_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/MiniBatchGradientDescentTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fabio/Desktop/linreg/linreg.tmp/gradientdescent_v1_0_project/gradientdescent_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/MiniBatchGradientDescentTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
